apiVersion: v2
name: erpc
description: eRPC with optional Bitnami Redis (shared state) and CloudNative-PG (EVM cache)
type: application
version: 0.1.21
appVersion: "latest"
dependencies:
  - alias: postgres
    name: cluster
    condition: postgres.enabled
    version: 0.3.1
    repository: https://cloudnative-pg.github.io/charts
  - name: redis
    condition: redis.enabled
    version: 25.3.5
    repository: https://charts.bitnami.com/bitnami
