apiVersion: v2
name: centrifuge-event-lake
description: Centrifuge event-lake ingestion (Envio indexer -> Redpanda protocol events)
type: application
version: 0.1.1
appVersion: "0.1.0"
dependencies:
  - alias: postgres
    name: cluster
    condition: postgres.enabled
    version: 0.3.1
    repository: https://cloudnative-pg.github.io/charts
