{{- if .Values.global.forceClean }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Release.Name }}-force-clean
  labels:
    {{- include "centrifuge-api.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  template:
    metadata:
      labels:
        {{- include "centrifuge-api.selectorLabels" . | nindent 8 }}
    spec:
      restartPolicy: Never
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: force-clean
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            - force-clean
          env:
            - name: DB_DATABASE
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.global.dbSecretName }}
                  key: dbname
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.global.dbSecretName }}
                  key: host
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.global.dbSecretName }}
                  key: user
            - name: DB_PASS
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.global.dbSecretName }}
                  key: password
            - name: DB_PORT
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.global.dbSecretName }}
                  key: port
          {{- with .Values.env }}
            {{- toYaml . | nindent 12 }}
          {{- end }}
          envFrom:
            - configMapRef:
                name: {{ .Release.Name }}-config
            - secretRef:
                name: {{ .Values.global.apiSecretName }}
          {{- with .Values.envFrom }}
            {{- toYaml . | nindent 12 }}
          {{- end }}
{{- end }} 