nameOverride: ""
fullnameOverride: ""
imagePullSecrets: []

global:
  chainId: centrifuge
  dbSecretName: centrifuge-api-dbConfig-secret
  apiSecretName: centrifuge-api-apiConfig-secret
  # ---
  # apiVersion: v1
  # kind: Secret
  # metadata:
  #   name: centrifuge-api-config-secret
  # type: Opaque
  # stringData:
  #   DB_PASS: {{ .Files.Get ".env" | fromEnv "DB_PASS" }}
  #   ONFINALITY_API_KEY: {{ .Files.Get ".env" | fromEnv "ONFINALITY_API_KEY" }}
  #   ALCHEMY_API_KEY: {{ .Files.Get ".env" | fromEnv "ALCHEMY_API_KEY" }}
  # ---

node-cfg:
  nodeId: centrifuge
  enabled: true
  image:
    repository: ghcr.io/centrifuge/api-cfg
    pullPolicy: Always
    tag: "2"

node-eth:
  nodeId: eth
  enabled: true
  image:
    repository: ghcr.io/centrifuge/api-evm
    pullPolicy: Always
    tag: "2"
  command:
    - --timeout=3600
    - --multi-chain
    - --db-schema=app
    - --disable-historical=true
    - --workers=0
    - --batch-size=30
    - --skipTransactions=true
    - --unsafe

node-base:
  nodeId: base
  enabled: false
  image:
    repository: ghcr.io/centrifuge/api-evm
    pullPolicy: Always
    tag: "2"
  command:
    - --timeout=3600
    - --multi-chain
    - --db-schema=app
    - --disable-historical=true
    - --workers=0
    - --batch-size=30
    - --skipTransactions=true
    - --unsafe
    
query:
  image:
    tag: "latest"
  ingress:
    enabled: false
    className: "traefik"
    annotations:
      kubernetes.io/tls-acme: "true"
      traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
      nginx.ingress.kubernetes.io/ssl-redirect: "true"
    hosts: []
    tls: []