{{- if .Values.global.forceClean }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Release.Name }}-force-clean
  labels:
    {{- include "centrifuge-api.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  template:
    metadata:
      labels:
        {{- include "centrifuge-api.selectorLabels" . | nindent 8 }}
    spec:
      restartPolicy: Never
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: force-clean
          image: "{{ index .Values "indexer" "image" "repository" }}:{{ index .Values "indexer" "image" "tag" }}"
          imagePullPolicy: {{ index .Values "indexer" "image" "pullPolicy" }}
          args:
            - db
            - prune
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.global.dbSecretName | default (printf "%s-postgres-app" .Release.Name) }}
                  key: uri
          envFrom:
            - configMapRef:
                name: {{ .Release.Name }}-config
            - secretRef:
                name: {{ .Values.global.apiSecretName }}
{{- end }}